# Generated by Django 4.2.4 on 2023-11-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('meaning', models.TextField()),
                ('example', models.TextField()),
                ('synonym', models.CharField(max_length=100)),
                ('antonym', models.CharField(max_length=100)),
            ],
        ),
    ]
