# Generated by Django 4.2.7 on 2023-12-01 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DictionaryApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='animation',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
